# Generated by Django 4.1.3 on 2023-03-07 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0005_product_credit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='credit',
        ),
    ]
